apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: netology
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - port: 80
      name: nginx-port
      targetPort: 80
      nodePort: 30011
    - port: 8080
      name: multitool-port
      targetPort: 8080
      nodePort: 30012